nc: 8 # number of classes
depth_multiple: 1.0  # scales module repeats
width_multiple: 1.0  # scales convolution channels
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  l: [ 1.00, 1.00, 512 ] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [ -1, 1, Conv, [ 64, 3, 2 ] ] # 0-P1/2
  - [ -1, 1, Conv, [ 128, 3, 2 ] ] # 1-P2/4
  - [ -1, 3, C2f, [ 128, True ] ]
  - [ -1, 1, Conv, [ 256, 3, 2 ] ] # 3-P3/8
  - [ -1, 6, C2f, [ 256, True ] ] # out 256
  - [ -1, 1, SCDown, [ 512, 3, 2 ] ] # 5-P4/16
  - [ -1, 6, C2f, [ 512, True ] ] # out 512
  - [ -1, 1, SCDown, [ 1024, 3, 2 ] ] # 7-P5/32
  - [ -1, 3, C2fCIB, [ 1024, True ] ]
  - [ -1, 1, SPPF, [ 1024, 5 ] ] # 9
  - [ -1, 1, PSA, [ 1024 ] ] # 10 out 1024