# Parameters
nc: 55  # number of classes
depth_multiple: 0.67  # scales module repeats
width_multiple: 0.75  # scales convolution channels

# YOLOv8.0m backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]] # 2
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8  192
  - [-1, 6, C2f, [256, True]] # 4 out 192
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16  384
  - [-1, 6, C2f, [512, True]] # 6 out 384
  - [-1, 1, Conv, [768, 3, 2]]  # 7-P5/32  576
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, SPPF, [768, 5]]  # 9  576 out