path: E:/python/CRTDETR/Cigarrette_Detection/  # dataset root dir
train: images/train  # train images (relative to 'path') 118287 images
val: images/val  # val images (relative to 'path') 5000 images

# Classes
names:
  0: Cigarette-Buds
  1: Bud


