path: E:/python/CRTDETR/RSOD_Dataset/  # dataset root dir
train: images/train  # train images (relative to 'path') 118287 images
val: images/val  # val images (relative to 'path') 5000 images

# Classes
names:
  0: aircraft
  1: oiltank
  2: overpass
  3: playground


