__include__: [
  '../dataset/algae.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/mdetr.yml',
]

RTDETR:
  multi_scale: [640, 640, 640]

YOLOBackbone:
  cfg: 'configs/rtdetr/include/backbonem.yml'

train_dataloader:
  batch_size: 8
  num_workers: 4

optimizer:
  params:
    - params: 'backbone'
      lr: 0.00002
  lr: 0.00005

use_amp: True
epoches: 100

output_dir: ./result/mdetr