__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/yolov7.yml',
]

YOLOBackbone:
  cfg: 'configs/rtdetr/include/backbone7.yml'

train_dataloader:
  batch_size: 8
  num_workers: 4

use_amp: False
epoches: 128


optimizer:
  params:
    - params: 'backbone'
      lr: 0.0001

output_dir: ./result/y7