__include__: [
  '../dataset/power_grid.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

RTDETR:
  multi_scale: [ 640, 640, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 960 ]

train_dataloader:
  batch_size: 4
  num_workers: 4

optimizer:
  params:
    - params: 'backbone'
      lr: 0.00002
  lr: 0.00005

use_amp: True
epoches: 100

output_dir: ./result/pgrt4